# exp 1
# loss: l2_loss
# optimizer: sgd

# epoches: 10
# num_units: 3

# # exp 2
loss: l2_loss
optimizer: sgd

epoches: 500
num_units: 3

# # exp 3
# loss: ce_loss
# optimizer: adam

# epoches: 100
# num_units: 128